def generate_report(itinerary, budget, hotels, weather):

    report = f"""
## 📅 Personalized Itinerary

{itinerary}

---

## 💰 Budget Analysis

{budget}

---

## 🏨 Hotel Recommendations

{hotels}

---

## 🌤 Weather Forecast

{weather}

---

### 🤖 Generated by Voyager AI Multi-Agent Platform
"""

    return report